name: Context
on: pull_request

jobs:
  functions:
    runs-on: ubuntu-18.04
    steps:
      - name: dump
        run: |
          echo ${{ contains('Hello', 'll') }}
          echo ${{ startsWith( 'hello', 'he') }}
          echo ${{ endsWith( 'hello', 'lo' ) }}
          echo ${{ format('Hello {0} {1} {2}', 'World', '!', '!' ) }}
  one:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push'   # if event that triggered the workflow is push then run this job, 
                                      # if something else like pull_requset then this job will not run.
                                      # this way we can make sure this job will only runs when event type is 'push'.
                                      # here event name is another github actions context.
    steps:
      - name: Dump Github Context     # this step will fail for testing 
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run:
          echho "$GITHUB_CONTEXT"     # typo in 'echho'
      - name: Dump Job Context
        if: failure()                 # runs only if previous step fails.
        env: 
          JOB_CONTEXT: ${{ toJson(job) }}
        run:
          echo "$JOB_CONTEXT"
      - name: Dump runner context
        if: always()                  # this step always runs what ever happens in previous steps.
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
    

        
